<?php
require('../datos/parse_str.php');
require_once("../datos/conex.php");
$ID_EVENTO_ADVERSOS = $ID_EVENTO_ADVERSO;
$hoy = date('Y-m-d');
$consulta = mysqli_query($conex, "SELECT * FROM ipsen_evento_adverso AS EA
INNER JOIN ipsen_pacientes AS P ON P.ID_PACIENTE=EA.ID_PACIENTE_FK
INNER JOIN ipsen_tratamiento AS T ON T.ID_PACIENTE_FK=P.ID_PACIENTE
WHERE EA.ID_EVENTO_ADVERSO='" . $ID_EVENTO_ADVERSOS . "'");
echo mysqli_error($conex);
while ($fila1 = mysqli_fetch_array($consulta)) {
	$ID_EVENTO_ADVERSO = $fila1['ID_EVENTO_ADVERSO'];
	$PAIS = $fila1['PAIS'];
	$TIPO_REPORTE = $fila1['TIPO_REPORTE'];
	$FECHA_STAFF = $fila1['FECHA_STAFF'];
	$PRODUCTO = $fila1['PRODUCTO'];
	$CIUDAD = $fila1['CIUDAD'];
	$GENERO = $fila1['GENERO'];
	$FECHA_NACIMIENTO = $fila1['FECHA_NACIMIENTO'];
	$EMBARAZO = $fila1['EMBARAZO'];
	$FECHA_PARTO = $fila1['FECHA_PARTO'];
	$DESENLACE = $fila1['DESENLACE'];
	$CUALES_DESENLACES = $fila1['CUALES_DESENLACES'];
	$CONTACTO_DIRECTO = $fila1['CONTACTO_DIRECTO'];
	$NOMBRE_MEDICO = $fila1['NOMBRE_MEDICO'];
	$TELEFONO_MEDICO = $fila1['TELEFONO_MEDICO'];
	$FAX_MEDICO = $fila1['FAX_MEDICO'];
	$EMAIL_MEDICO = $fila1['EMAIL_MEDICO'];
	$INDICACION1 = $fila1['INDICACION1'];
	$FORMULACION1 = $fila1['FORMULACION1'];
	$REGIMEN_DOSIS1 = $fila1['REGIMEN_DOSIS1'];
	$RUTA_ADMINISTRACION1 = $fila1['RUTA_ADMINISTRACION1'];
	$NUMERO_LOTE1 = $fila1['NUMERO_LOTE1'];
	$FECHA_EXPIRACION1 = $fila1['FECHA_EXPIRACION1'];
	$FECHA_INICIO1 = $fila1['FECHA_INICIO1'];
	$TRATAMIENTO_CONTINUA1 = $fila1['TRATAMIENTO_CONTINUA1'];
	$INDICACION2 = $fila1['INDICACION2'];
	$FORMULACION2 = $fila1['FORMULACION2'];
	$REGIMEN_DOSIS2 = $fila1['REGIMEN_DOSIS2'];
	$RUTA_ADMINISTRACION2 = $fila1['RUTA_ADMINISTRACION2'];
	$NUMERO_LOTE2 = $fila1['NUMERO_LOTE2'];
	$FECHA_EXPIRACION2 = $fila1['FECHA_EXPIRACION2'];
	$FECHA_INICIO2 = $fila1['FECHA_INICIO2'];
	$TRATAMIENTO_CONTINUA2 = $fila1['TRATAMIENTO_CONTINUA2'];
	$INDICACION3 = $fila1['INDICACION3'];
	$FORMULACION3 = $fila1['FORMULACION3'];
	$REGIMEN_DOSIS3 = $fila1['REGIMEN_DOSIS3'];
	$RUTA_ADMINISTRACION3 = $fila1['RUTA_ADMINISTRACION3'];
	$NUMERO_LOTE3 = $fila1['NUMERO_LOTE3'];
	$FECHA_EXPIRACION3 = $fila1['FECHA_EXPIRACION3'];
	$FECHA_INICIO3 = $fila1['FECHA_INICIO3'];
	$TRATAMIENTO_CONTINUA3 = $fila1['TRATAMIENTO_CONTINUA3'];
	$MUESTRA_DISPONIBLE = $fila1['MUESTRA_DISPONIBLE'];
	$INFORMACION_MUESTRA = $fila1['INFORMACION_MUESTRA'];
	$RELACION_MEDICAMENTO1 = $fila1['RELACION_MEDICAMENTO1'];
	$RELACIONADO_DISPOSITIVO1 = $fila1['RELACIONADO_DISPOSITIVO1'];
	$FECHA_INICIO_EVENTO1 = $fila1['FECHA_INICIO_EVENTO1'];
	$DESENLACE1 = $fila1['DESENLACE1'];
	$FECHA_RECUPERACION1 = $fila1['FECHA_RECUPERACION1'];
	$FECHA_MUERTE1 = $fila1['FECHA_MUERTE1'];
	$CRITERIO_SERIEDAD1 = $fila1['CRITERIO_SERIEDAD1'];
	$CRITERIO_SERIEDAD_MUERTE1 = $fila1['CRITERIO_SERIEDAD_MUERTE1'];
	$CRITERIO_SERIEDAD_HOSPITALIZACION1 = $fila1['CRITERIO_SERIEDAD_HOSPITALIZACION1'];
	$CRITERIO_SERIEDAD_AMENAZA1 = $fila1['CRITERIO_SERIEDAD_AMENAZA1'];
	$CRITERIO_SERIEDAD_INCAPACIDAD1 = $fila1['CRITERIO_SERIEDAD_INCAPACIDAD1'];
	$CRITERIO_SERIEDAD_ANORMALIDAD1 = $fila1['CRITERIO_SERIEDAD_ANORMALIDAD1'];
	$CRITERIO_SERIEDAD_EVENTO1 = $fila1['CRITERIO_SERIEDAD_EVENTO1'];
	$CRITERIO_SERIEDAD_QUIRURGICA1 = $fila1['CRITERIO_SERIEDAD_QUIRURGICA1'];
	$CAUSA_MUERTE1 = $fila1['CAUSA_MUERTE1'];
	$DETALLES_EA1 = $fila1['DETALLES_EA1'];
	$RELACION_MEDICAMENTO2 = $fila1['RELACION_MEDICAMENTO2'];
	$RELACIONADO_DISPOSITIVO2 = $fila1['RELACIONADO_DISPOSITIVO2'];
	$FECHA_INICIO_EVENTO2 = $fila1['FECHA_INICIO_EVENTO2'];
	$DESENLACE2 = $fila1['DESENLACE2'];
	$FECHA_RECUPERACION2 = $fila1['FECHA_RECUPERACION2'];
	$FECHA_MUERTE2 = $fila1['FECHA_MUERTE2'];
	$CRITERIO_SERIEDAD2 = $fila1['CRITERIO_SERIEDAD2'];
	$CRITERIO_SERIEDAD_MUERTE2 = $fila1['CRITERIO_SERIEDAD_MUERTE2'];
	$CRITERIO_SERIEDAD_HOSPITALIZACION2 = $fila1['CRITERIO_SERIEDAD_HOSPITALIZACION2'];
	$CRITERIO_SERIEDAD_AMENAZA2 = $fila1['CRITERIO_SERIEDAD_AMENAZA2'];
	$CRITERIO_SERIEDAD_INCAPACIDAD2 = $fila1['CRITERIO_SERIEDAD_INCAPACIDAD2'];
	$CRITERIO_SERIEDAD_ANORMALIDAD2 = $fila1['CRITERIO_SERIEDAD_ANORMALIDAD2'];
	$CRITERIO_SERIEDAD_EVENTO2 = $fila1['CRITERIO_SERIEDAD_EVENTO2'];
	$CRITERIO_SERIEDAD_QUIRURGICA2 = $fila1['CRITERIO_SERIEDAD_QUIRURGICA2'];
	$CAUSA_MUERTE2 = $fila1['CAUSA_MUERTE2'];
	$DETALLES_EA2 = $fila1['DETALLES_EA2'];
	$RELACION_MEDICAMENTO3 = $fila1['RELACION_MEDICAMENTO3'];
	$RELACIONADO_DISPOSITIVO3 = $fila1['RELACIONADO_DISPOSITIVO3'];
	$FECHA_INICIO_EVENTO3 = $fila1['FECHA_INICIO_EVENTO3'];
	$DESENLACE3 = $fila1['DESENLACE3'];
	$FECHA_RECUPERACION3 = $fila1['FECHA_RECUPERACION3'];
	$FECHA_MUERTE3 = $fila1['FECHA_MUERTE3'];
	$CRITERIO_SERIEDAD3 = $fila1['CRITERIO_SERIEDAD3'];
	$CRITERIO_SERIEDAD_MUERTE3 = $fila1['CRITERIO_SERIEDAD_MUERTE3'];
	$CRITERIO_SERIEDAD_HOSPITALIZACION3 = $fila1['CRITERIO_SERIEDAD_HOSPITALIZACION3'];
	$CRITERIO_SERIEDAD_AMENAZA3 = $fila1['CRITERIO_SERIEDAD_AMENAZA3'];
	$CRITERIO_SERIEDAD_INCAPACIDAD3 = $fila1['CRITERIO_SERIEDAD_INCAPACIDAD3'];
	$CRITERIO_SERIEDAD_ANORMALIDAD3 = $fila1['CRITERIO_SERIEDAD_ANORMALIDAD3'];
	$CRITERIO_SERIEDAD_EVENTO3 = $fila1['CRITERIO_SERIEDAD_EVENTO3'];
	$CRITERIO_SERIEDAD_QUIRURGICA3 = $fila1['CRITERIO_SERIEDAD_QUIRURGICA3'];
	$CAUSA_MUERTE3 = $fila1['CAUSA_MUERTE3'];
	$DETALLES_EA3 = $fila1['DETALLES_EA3'];
	$INFORMACION_ADICIONAL = $fila1['INFORMACION_ADICIONAL'];
	$NOMBRE_REPORTE = $fila1['NOMBRE_REPORTE'];
	$ID_PACIENTE_FK = $fila1['ID_PACIENTE_FK'];
	$MEDICAMENTO1 = $fila1['MEDICAMENTO1'];
	$MEDICAMENTO2 = $fila1['MEDICAMENTO2'];
	$MEDICAMENTO3 = $fila1['MEDICAMENTO3'];
	$INFORMACION_EA1 = $fila1['INFORMACION_EA1'];
	$INFORMACION_EA2 = $fila1['INFORMACION_EA2'];
	$INFORMACION_EA3 = $fila1['INFORMACION_EA3'];
	$NOMBRE_PACIENTE = $fila1['NOMBRE_PACIENTE'];
	$APELLIDO_PACIENTE = $fila1['APELLIDO_PACIENTE'];
	$IDENTIFICACION_PACIENTE = $fila1['IDENTIFICACION_PACIENTE'];
	$DIRECCION_PACIENTE = $fila1['DIRECCION_PACIENTE'];
	$CIUDAD_PACIENTE = $fila1['CIUDAD_PACIENTE'];
	$TELEFONO_PACIENTE = $fila1['TELEFONO_PACIENTE'];
	$CORREO_PACIENTE = $fila1['CORREO_PACIENTE'];
	$FECHA_SUSPENCION1 = $fila1['FECHA_SUSPENCION1'];
	$FECHA_SUSPENCION2 = $fila1['FECHA_SUSPENCION2'];
	$FECHA_SUSPENCION3 = $fila1['FECHA_SUSPENCION3'];
	$NOMBRE_REPORTANTE_PRIMARIO = $fila1['NOMBRE_REPORTANTE_PRIMARIO'];
	$TELEFONO_REPORTANTE_PRIMARIO = $fila1['TELEFONO_REPORTANTE_PRIMARIO'];
	$TIPO_REPORTANTE = $fila1['TIPO_REPORTANTE'];
}
if ($GENERO == 'M') {
	$GENERO = 'MASCULINO';
}
if ($GENERO == 'F') {
	$GENERO = 'FEMENINO';
}
$nombre = $NOMBRE_PACIENTE . ' ' . $APELLIDO_PACIENTE;
function iniciales($nombre)
{
	$notocar = array('del', 'de');
	$trozos = explode(' ', $nombre);
	$iniciales = '';
	for ($i = 0; $i < count($trozos); $i++) {
		if (in_array($trozos[$i], $notocar)) $iniciales .= $trozos[$i] . " ";
		else $iniciales .= substr($trozos[$i], 0, 1) . ". ";
	}
	return $iniciales;
}
