<?php
require('../datos/parse_str.php');
require('../datos/conex.php');
if (isset($_POST['buscar'])) {
	$TIPO_SOLICITUD = $_POST['TIPO_SOLICITUD'];
}
if ($TIPO_SOLICITUD == 'ENTREGADO') {
	$SELECT_SOLICITUDES_TOTAL = mysqli_query($conex, "SELECT * FROM ipsen_inventario AS I
	INNER JOIN ipsen_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN ipsen_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.ESTADO_MOVIMIENTO='ENTREGADO' AND RESPONSABLE='fundem' ORDER BY M.FECHA_MOVIMIENTO ASC");
	echo mysqli_error($conex);
	$SELECT_SOLICITUDES = "SELECT * FROM ipsen_inventario AS I
	INNER JOIN ipsen_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN ipsen_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.ESTADO_MOVIMIENTO='ENTREGADO' AND RESPONSABLE='fundem' ORDER BY M.FECHA_MOVIMIENTO ASC LIMIT";
}
if ($TIPO_SOLICITUD == 'PENDIENTES') {
	$SELECT_SOLICITUDES_TOTAL = mysqli_query($conex, "SELECT * FROM ipsen_inventario AS I
	INNER JOIN ipsen_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN ipsen_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.ESTADO_MOVIMIENTO='EN PROCESO' AND RESPONSABLE='fundem' ORDER BY M.FECHA_MOVIMIENTO ASC");
	echo mysqli_error($conex);
	$SELECT_SOLICITUDES = "SELECT * FROM ipsen_inventario AS I
	INNER JOIN ipsen_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN ipsen_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.ESTADO_MOVIMIENTO='EN PROCESO' AND RESPONSABLE='fundem' ORDER BY M.FECHA_MOVIMIENTO ASC LIMIT";
}
if ($TIPO_SOLICITUD == 'DESPACHADOS') {
	$SELECT_SOLICITUDES_TOTAL = mysqli_query($conex, "SELECT * FROM ipsen_inventario AS I
	INNER JOIN ipsen_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN ipsen_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.ESTADO_MOVIMIENTO='DESPACHADO' AND RESPONSABLE='fundem' ORDER BY M.FECHA_MOVIMIENTO ASC");
	echo mysqli_error($conex);
	$SELECT_SOLICITUDES = "SELECT * FROM ipsen_inventario AS I
	INNER JOIN ipsen_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN ipsen_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.ESTADO_MOVIMIENTO='DESPACHADO' AND RESPONSABLE='fundem' ORDER BY M.FECHA_MOVIMIENTO ASC LIMIT";
}
