<?php
require('../datos/parse_str.php');
require('../datos/conex.php');
if (isset($_POST['buscar'])) {
	$fecha_ini = $_POST['fecha_ini'] . ' 00:00:00';
	$fecha_fin = $_POST['fecha_fin'] . ' 23:59:59';
	$TIPO_SOLICITUD = $_POST['TIPO_SOLICITUD'];
}
if ($TIPO_SOLICITUD == 'ENTREGADO') {
	$SELECT_SOLICITUDES_TOTAL = mysqli_query($conex, "SELECT * FROM bayer_inventario AS I
	INNER JOIN bayer_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN bayer_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	INNER JOIN bayer_pacientes AS P ON P.ID_PACIENTE=I.LUGAR_MATERIAL
	INNER JOIN bayer_paciente_movimientos AS PM ON PM.ID_MOVIMIENTOS_FK=M.ID_MOVIMIENTOS
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.ESTADO_MOVIMIENTO='ENTREGADO' ORDER BY M.FECHA_MOVIMIENTO ASC");
	echo mysqli_error($conex);
	$SELECT_SOLICITUDES = "SELECT * FROM bayer_inventario AS I
	INNER JOIN bayer_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN bayer_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	INNER JOIN bayer_pacientes AS P ON P.ID_PACIENTE=I.LUGAR_MATERIAL
	INNER JOIN bayer_paciente_movimientos AS PM ON PM.ID_MOVIMIENTOS_FK=M.ID_MOVIMIENTOS
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.ESTADO_MOVIMIENTO='ENTREGADO' ORDER BY M.FECHA_MOVIMIENTO ASC LIMIT";
}
if ($TIPO_SOLICITUD == 'PENDIENTES') {
	if ($fecha_ini != ' 00:00:00' || $fecha_fin != ' 23:59:59') {
		$SELECT_SOLICITUDES_TOTAL = mysqli_query($conex, "SELECT * FROM bayer_movimientos AS M INNER JOIN bayer_referencia AS R ON R.ID_REFERENCIA=M.ID_REFERENCIA_FK INNER JOIN bayer_paciente_movimientos AS PM ON PM.ID_MOVIMIENTOS_FK=M.ID_MOVIMIENTOS
		INNER JOIN bayer_pacientes AS P ON P.ID_PACIENTE=PM.ID_PACIENTE_FK WHERE
		M.FECHA_MOVIMIENTO>='" . $fecha_ini . "' AND M.FECHA_MOVIMIENTO<='" . $fecha_fin . "' AND M.ESTADO_MOVIMIENTO='EN PROCESO' ORDER BY M.FECHA_MOVIMIENTO ASC");
		echo mysqli_error($conex);
		$SELECT_SOLICITUDES = "SELECT * FROM bayer_movimientos AS M INNER JOIN bayer_referencia AS R ON R.ID_REFERENCIA=M.ID_REFERENCIA_FK INNER JOIN bayer_paciente_movimientos AS PM ON PM.ID_MOVIMIENTOS_FK=M.ID_MOVIMIENTOS
		INNER JOIN bayer_pacientes AS P ON P.ID_PACIENTE=PM.ID_PACIENTE_FK WHERE
		M.FECHA_MOVIMIENTO>='" . $fecha_ini . "' AND M.FECHA_MOVIMIENTO<='" . $fecha_fin . "' AND M.ESTADO_MOVIMIENTO='EN PROCESO' ORDER BY M.FECHA_MOVIMIENTO ASC LIMIT";
	}
	if ($fecha_ini == ' 00:00:00' || $fecha_fin == ' 23:59:59') {
		$SELECT_SOLICITUDES_TOTAL = mysqli_query($conex, "SELECT * FROM bayer_movimientos AS M INNER JOIN bayer_referencia AS R ON R.ID_REFERENCIA=M.ID_REFERENCIA_FK INNER JOIN bayer_paciente_movimientos AS PM ON PM.ID_MOVIMIENTOS_FK=M.ID_MOVIMIENTOS
		INNER JOIN bayer_pacientes AS P ON P.ID_PACIENTE=PM.ID_PACIENTE_FK WHERE
		M.ESTADO_MOVIMIENTO='EN PROCESO' ORDER BY M.FECHA_MOVIMIENTO ASC");
		echo mysqli_error($conex);
		$SELECT_SOLICITUDES = "SELECT * FROM bayer_movimientos AS M INNER JOIN bayer_referencia AS R ON R.ID_REFERENCIA=M.ID_REFERENCIA_FK INNER JOIN bayer_paciente_movimientos AS PM ON PM.ID_MOVIMIENTOS_FK=M.ID_MOVIMIENTOS
		INNER JOIN bayer_pacientes AS P ON P.ID_PACIENTE=PM.ID_PACIENTE_FK WHERE
		M.ESTADO_MOVIMIENTO='EN PROCESO' ORDER BY M.FECHA_MOVIMIENTO ASC LIMIT";
	}
}
if ($TIPO_SOLICITUD == 'DESPACHADOS') {
	$SELECT_SOLICITUDES_TOTAL = mysqli_query($conex, "SELECT * FROM bayer_inventario AS I
	INNER JOIN bayer_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN bayer_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	INNER JOIN bayer_pacientes AS P ON P.ID_PACIENTE=I.LUGAR_MATERIAL
	INNER JOIN bayer_paciente_movimientos AS PM ON PM.ID_MOVIMIENTOS_FK=M.ID_MOVIMIENTOS
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.FECHA_MOVIMIENTO>='" . $fecha_ini . "' AND M.FECHA_MOVIMIENTO<='" . $fecha_fin . "' AND M.ESTADO_MOVIMIENTO='DESPACHADO' ORDER BY M.FECHA_MOVIMIENTO ASC");
	echo mysqli_error($conex);
	$SELECT_SOLICITUDES = "SELECT * FROM bayer_inventario AS I
	INNER JOIN bayer_referencia AS R ON R.ID_REFERENCIA=I.ID_REFERENCIA_FK
	INNER JOIN bayer_movimientos AS M ON I.ID_INVENTARIO=M.ID_INVENTARIO_FK
	INNER JOIN bayer_pacientes AS P ON P.ID_PACIENTE=I.LUGAR_MATERIAL
	INNER JOIN bayer_paciente_movimientos AS PM ON PM.ID_MOVIMIENTOS_FK=M.ID_MOVIMIENTOS
	WHERE I.LUGAR_MATERIAL!='BODEGA' AND M.TIPO_MOVIMIENTO='2' AND M.FECHA_MOVIMIENTO>='" . $fecha_ini . "' AND M.FECHA_MOVIMIENTO<='" . $fecha_fin . "' AND M.ESTADO_MOVIMIENTO='DESPACHADO' ORDER BY M.FECHA_MOVIMIENTO ASC LIMIT";
}
