<?php
require_once('session.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>IPSEN</title>
	<style>
		.aviso3 {
			font-size: 130%;
			font-weight: bold;
			color: #11a9e3;
			text-transform: uppercase;
			background-color: transparent;
			text-align: center;
			padding: 10px;
		}
		.error {
			font-size: 130%;
			font-weight: bold;
			color: #fb8305;
			text-transform: uppercase;
			background-color: transparent;
			text-align: center;
			padding: 10px;
		}
		.btn_continuar {
			padding-top: 7px;
			width: 152px;
			height: 37px;
			color: transparent;
			background-color: transparent;
			border-radius: 5px;
			border: 1px solid transparent;
		}
		.btn_continuar:active {
			box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.2);
			box-shadow: 0px 0px 30px rgba(0, 0, 0, 0.3),
				inset 0px 0px 20px #EEECEC;
		}
		.btn_continuar:hover {
			box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.2);
			box-shadow: 0px 0px 30px rgba(0, 0, 0, 0.3),
				inset 0px 0px 20px #EEECEC;
		}
	</style>
</head>
<body>
	<?php
require('../datos/parse_str.php');
	require_once("../datos/conex.php");
	if (isset($_POST['registrar'])) {
		$PAIS = $_POST['PAIS'];
		$TIPO_REPORTE = $_POST['TIPO_REPORTE'];
		$FECHA_STAFF = $_POST['FECHA_STAFF'];
		$PRODUCTO = $_POST['PSP_PRODUCTO'];
		$CIUDAD = $_POST['CIUDAD'];
		$GENERO = $_POST['GENERO'];
		$FECHA_NACIMIENTO = $_POST['FECHA_NACIMIENTO'];
		$EMBARAZO = $_POST['EMBARAZO'];
		$FECHA_PARTO = $_POST['FECHA_PARTO'];
		$DESENLACE = $_POST['DESENLACE'];
		$CUALES_DESENLACES = $_POST['Cuales'];
		$CONTACTO_DIRECTO = $_POST['PERMITE_CONTACTO'];
		$NOMBRE_MEDICO = $_POST['NOMBRE_MEDICO'];
		$TELEFONO_MEDICO = $_POST['TELEFONO_MEDICO'];
		$FAX_MEDICO = $_POST['FAX_MEDICO'];
		$EMAIL_MEDICO = $_POST['EMAIL_MEDICO'];
		$INDICACION1 = $_POST['INDICACION1'];
		$FORMULACION1 = $_POST['FORMULACION1'];
		$REGIMEN_DOSIS1 = $_POST['REGIMEN_DOSIS1'];
		$RUTA_ADMINISTRACION1 = $_POST['RUTA_ADMINISTRACION1'];
		$NUMERO_LOTE1 = $_POST['NUMERO_LOTE1'];
		$FECHA_EXPIRACION1 = $_POST['FECHA_EXPIRACION1'];
		$FECHA_INICIO1 = $_POST['FECHA_INICIO1'];
		$TRATAMIENTO_CONTINUA1 = $_POST['TRATAMIENTO_CONTINUA1'];
		$INDICACION2 = $_POST['INDICACION2'];
		$FORMULACION2 = $_POST['FORMULACION2'];
		$REGIMEN_DOSIS2 = $_POST['REGIMEN_DOSIS2'];
		$RUTA_ADMINISTRACION2 = $_POST['RUTA_ADMINISTRACION2'];
		$NUMERO_LOTE2 = $_POST['NUMERO_LOTE2'];
		$FECHA_EXPIRACION2 = $_POST['FECHA_EXPIRACION2'];
		$FECHA_INICIO2 = $_POST['FECHA_INICIO2'];
		$TRATAMIENTO_CONTINUA2 = $_POST['TRATAMIENTO_CONTINUA2'];
		$INDICACION3 = $_POST['INDICACION3'];
		$FORMULACION3 = $_POST['FORMULACION3'];
		$REGIMEN_DOSIS3 = $_POST['REGIMEN_DOSIS3'];
		$RUTA_ADMINISTRACION3 = $_POST['RUTA_ADMINISTRACION3'];
		$NUMERO_LOTE3 = $_POST['NUMERO_LOTE3'];
		$FECHA_EXPIRACION3 = $_POST['FECHA_EXPIRACION3'];
		$FECHA_INICIO3 = $_POST['FECHA_INICIO3'];
		$TRATAMIENTO_CONTINUA3 = $_POST['TRATAMIENTO_CONTINUA3'];
		$MUESTRA_DISPONIBLE = $_POST['MUESTRA_DISPONIBLE'];
		$INFORMACION_MUESTRA = $_POST['INFORMACION_MUESTRA'];
		$RELACION_MEDICAMENTO1 = $_POST['RELACION_MEDICAMENTO1'];
		$RELACIONADO_DISPOSITIVO1 = $_POST['RELACIONADO_DISPOSITIVO1'];
		$FECHA_INICIO_EVENTO1 = $_POST['FECHA_INICIO_EVENTO1'];
		$DESENLACE1 = $_POST['DESENLACE1'];
		$FECHA_RECUPERACION1 = $_POST['FECHA_RECUPERACION1'];
		$FECHA_MUERTE1 = $_POST['FECHA_MUERTE1'];
		$CRITERIO_SERIEDAD1 = $_POST['CRITERIO_SERIEDAD1'];
		$CRITERIO_SERIEDAD_MUERTE1 = $_POST['CRITERIO_SERIEDAD_MUERTE1'];
		$CRITERIO_SERIEDAD_HOSPITALIZACION1 = $_POST['CRITERIO_SERIEDAD_HOSPITALIZACION1'];
		$CRITERIO_SERIEDAD_AMENAZA1 = $_POST['CRITERIO_SERIEDAD_AMENAZA1'];
		$CRITERIO_SERIEDAD_INCAPACIDAD1 = $_POST['CRITERIO_SERIEDAD_INCAPACIDAD1'];
		$CRITERIO_SERIEDAD_ANORMALIDAD1 = $_POST['CRITERIO_SERIEDAD_ANORMALIDAD1'];
		$CRITERIO_SERIEDAD_EVENTO1 = $_POST['CRITERIO_SERIEDAD_EVENTO1'];
		$CRITERIO_SERIEDAD_QUIRURGICA1 = $_POST['CRITERIO_SERIEDAD_QUIRURGICA1'];
		$CAUSA_MUERTE1 = $_POST['CAUSA_MUERTE1'];
		$DETALLES_EA1 = $_POST['DETALLES_EA1'];
		$RELACION_MEDICAMENTO2 = $_POST['RELACION_MEDICAMENTO2'];
		$RELACIONADO_DISPOSITIVO2 = $_POST['RELACIONADO_DISPOSITIVO2'];
		$FECHA_INICIO_EVENTO2 = $_POST['FECHA_INICIO_EVENTO2'];
		$DESENLACE2 = $_POST['DESENLACE2'];
		$FECHA_RECUPERACION2 = $_POST['FECHA_RECUPERACION2'];
		$FECHA_MUERTE2 = $_POST['FECHA_MUERTE2'];
		$CRITERIO_SERIEDAD2 = $_POST['CRITERIO_SERIEDAD2'];
		$CRITERIO_SERIEDAD_MUERTE2 = $_POST['CRITERIO_SERIEDAD_MUERTE2'];
		$CRITERIO_SERIEDAD_HOSPITALIZACION2 = $_POST['CRITERIO_SERIEDAD_HOSPITALIZACION2'];
		$CRITERIO_SERIEDAD_AMENAZA2 = $_POST['CRITERIO_SERIEDAD_AMENAZA2'];
		$CRITERIO_SERIEDAD_INCAPACIDAD2 = $_POST['CRITERIO_SERIEDAD_INCAPACIDAD2'];
		$CRITERIO_SERIEDAD_ANORMALIDAD2 = $_POST['CRITERIO_SERIEDAD_ANORMALIDAD2'];
		$CRITERIO_SERIEDAD_EVENTO2 = $_POST['CRITERIO_SERIEDAD_EVENTO2'];
		$CRITERIO_SERIEDAD_QUIRURGICA2 = $_POST['CRITERIO_SERIEDAD_QUIRURGICA2'];
		$CAUSA_MUERTE2 = $_POST['CAUSA_MUERTE2'];
		$DETALLES_EA2 = $_POST['DETALLES_EA2'];
		$RELACION_MEDICAMENTO3 = $_POST['RELACION_MEDICAMENTO3'];
		$RELACIONADO_DISPOSITIVO3 = $_POST['RELACIONADO_DISPOSITIVO3'];
		$FECHA_INICIO_EVENTO3 = $_POST['FECHA_INICIO_EVENTO3'];
		$DESENLACE3 = $_POST['DESENLACE3'];
		$FECHA_RECUPERACION3 = $_POST['FECHA_RECUPERACION3'];
		$FECHA_MUERTE3 = $_POST['FECHA_MUERTE3'];
		$CRITERIO_SERIEDAD3 = $_POST['CRITERIO_SERIEDAD3'];
		$CRITERIO_SERIEDAD_MUERTE3 = $_POST['CRITERIO_SERIEDAD_MUERTE3'];
		$CRITERIO_SERIEDAD_HOSPITALIZACION3 = $_POST['CRITERIO_SERIEDAD_HOSPITALIZACION3'];
		$CRITERIO_SERIEDAD_AMENAZA3 = $_POST['CRITERIO_SERIEDAD_AMENAZA3'];
		$CRITERIO_SERIEDAD_INCAPACIDAD3 = $_POST['CRITERIO_SERIEDAD_INCAPACIDAD3'];
		$CRITERIO_SERIEDAD_ANORMALIDAD3 = $_POST['CRITERIO_SERIEDAD_ANORMALIDAD3'];
		$CRITERIO_SERIEDAD_EVENTO3 = $_POST['CRITERIO_SERIEDAD_EVENTO3'];
		$CRITERIO_SERIEDAD_QUIRURGICA3 = $_POST['CRITERIO_SERIEDAD_QUIRURGICA3'];
		$CAUSA_MUERTE3 = $_POST['CAUSA_MUERTE3'];
		$DETALLES_EA3 = $_POST['DETALLES_EA3'];
		$INFORMACION_ADICIONAL = $_POST['INFORMACION_ADICIONAL'];
		$NOMBRE_REPORTE = $_POST['NOMBRE_REPORTE'];
		$COMPANIA = $_POST['COMPANIA'];
		$DIRECCION_COMPANIA = $_POST['DIRECCION_COMPANIA'];
		$TELEFONO_COMPANIA = $_POST['TELEFONO_COMPANIA'];
		$MEDICAMENTO1 = $_POST['MEDICAMENTO1'];
		$MEDICAMENTO2 = $_POST['MEDICAMENTO2'];
		$MEDICAMENTO3 = $_POST['MEDICAMENTO3'];
		$INFORMACION_EA1 = $_POST['INFORMACION_EA1'];
		$INFORMACION_EA2 = $_POST['INFORMACION_EA2'];
		$INFORMACION_EA3 = $_POST['INFORMACION_EA3'];
		$FECHA_SUSPENCION1 = $_POST['FECHA_SUSPENCION1'];
		$FECHA_SUSPENCION2 = $_POST['FECHA_SUSPENCION2'];
		$FECHA_SUSPENCION3 = $_POST['FECHA_SUSPENCION3'];
		$NOMBRE_REPORTANTES = $_POST['NOMBRE_PACIENTE'];
		$TELEFONO_REPORTANTE = $_POST['TELEFONO_PACIENTE'];
		$TIPO_REPORTANTES = $_POST['TIPO_REPORTANTE'];
		if ($TIPO_REPORTANTES == 'OTRO') {
			$TIPO_REPORTANTE_OTRO = $_POST['TIPO_REPORTANTE_OTRO'];
			$TIPO_REPORTANTE = $TIPO_REPORTANTES . ' ' . $TIPO_REPORTANTE_OTRO;
		} else {
			$TIPO_REPORTANTE = $TIPO_REPORTANTES;
		}
		$ID_PACIENTE_FK = $_POST['ID_PACIENTE'];
		$insertar = mysqli_query($conex,"INSERT INTO bayer_evento_adverso(PAIS,TIPO_REPORTE,FECHA_STAFF,PRODUCTO,CIUDAD,GENERO,FECHA_NACIMIENTO,EMBARAZO,FECHA_PARTO,DESENLACE,CUALES_DESENLACES,CONTACTO_DIRECTO,NOMBRE_MEDICO,TELEFONO_MEDICO,FAX_MEDICO,EMAIL_MEDICO,INDICACION1,FORMULACION1,REGIMEN_DOSIS1,RUTA_ADMINISTRACION1,NUMERO_LOTE1,FECHA_EXPIRACION1,FECHA_INICIO1,TRATAMIENTO_CONTINUA1,INDICACION2,FORMULACION2,REGIMEN_DOSIS2,RUTA_ADMINISTRACION2,NUMERO_LOTE2,FECHA_EXPIRACION2,FECHA_INICIO2,TRATAMIENTO_CONTINUA2,INDICACION3,FORMULACION3,REGIMEN_DOSIS3,RUTA_ADMINISTRACION3,NUMERO_LOTE3,FECHA_EXPIRACION3,FECHA_INICIO3,TRATAMIENTO_CONTINUA3,MUESTRA_DISPONIBLE,INFORMACION_MUESTRA,RELACION_MEDICAMENTO1,RELACIONADO_DISPOSITIVO1,FECHA_INICIO_EVENTO1,DESENLACE1,FECHA_RECUPERACION1,FECHA_MUERTE1,CRITERIO_SERIEDAD1,CRITERIO_SERIEDAD_MUERTE1,CRITERIO_SERIEDAD_HOSPITALIZACION1,CRITERIO_SERIEDAD_AMENAZA1,CRITERIO_SERIEDAD_INCAPACIDAD1,CRITERIO_SERIEDAD_ANORMALIDAD1,CRITERIO_SERIEDAD_EVENTO1,CRITERIO_SERIEDAD_QUIRURGICA1,CAUSA_MUERTE1,DETALLES_EA1,RELACION_MEDICAMENTO2,RELACIONADO_DISPOSITIVO2,FECHA_INICIO_EVENTO2,DESENLACE2,FECHA_RECUPERACION2,FECHA_MUERTE2,CRITERIO_SERIEDAD2,CRITERIO_SERIEDAD_MUERTE2,CRITERIO_SERIEDAD_HOSPITALIZACION2,CRITERIO_SERIEDAD_AMENAZA2,CRITERIO_SERIEDAD_INCAPACIDAD2,CRITERIO_SERIEDAD_ANORMALIDAD2,CRITERIO_SERIEDAD_EVENTO2,CRITERIO_SERIEDAD_QUIRURGICA2,CAUSA_MUERTE2,DETALLES_EA2,RELACION_MEDICAMENTO3,RELACIONADO_DISPOSITIVO3,FECHA_INICIO_EVENTO3,DESENLACE3,FECHA_RECUPERACION3,FECHA_MUERTE3,CRITERIO_SERIEDAD3,CRITERIO_SERIEDAD_MUERTE3,CRITERIO_SERIEDAD_HOSPITALIZACION3,CRITERIO_SERIEDAD_AMENAZA3,CRITERIO_SERIEDAD_INCAPACIDAD3,CRITERIO_SERIEDAD_ANORMALIDAD3,CRITERIO_SERIEDAD_EVENTO3,CRITERIO_SERIEDAD_QUIRURGICA3,CAUSA_MUERTE3,DETALLES_EA3,INFORMACION_ADICIONAL,NOMBRE_REPORTE,ID_PACIENTE_FK,MEDICAMENTO1,MEDICAMENTO2,MEDICAMENTO3,INFORMACION_EA1,INFORMACION_EA2,INFORMACION_EA3,FECHA_SUSPENCION1,FECHA_SUSPENCION2,FECHA_SUSPENCION3,NOMBRE_REPORTANTE_PRIMARIO,TELEFONO_REPORTANTE_PRIMARIO,TIPO_REPORTANTE)
		VALUES
		('" . $PAIS . "','" . $TIPO_REPORTE . "','" . $FECHA_STAFF . "','" . $PRODUCTO . "','" . $CIUDAD . "','" . $GENERO . "','" . $FECHA_NACIMIENTO . "','" . $EMBARAZO . "','" . $FECHA_PARTO . "','" . $DESENLACE . "','" . $CUALES_DESENLACES . "','" . $CONTACTO_DIRECTO . "','" . $NOMBRE_MEDICO . "','" . $TELEFONO_MEDICO . "','" . $FAX_MEDICO . "','" . $EMAIL_MEDICO . "','" . $INDICACION1 . "','" . $FORMULACION1 . "','" . $REGIMEN_DOSIS1 . "','" . $RUTA_ADMINISTRACION1 . "','" . $NUMERO_LOTE1 . "','" . $FECHA_EXPIRACION1 . "','" . $FECHA_INICIO1 . "','" . $TRATAMIENTO_CONTINUA1 . "','" . $INDICACION2 . "','" . $FORMULACION2 . "','" . $REGIMEN_DOSIS2 . "','" . $RUTA_ADMINISTRACION2 . "','" . $NUMERO_LOTE2 . "','" . $FECHA_EXPIRACION2 . "','" . $FECHA_INICIO2 . "','" . $TRATAMIENTO_CONTINUA2 . "','" . $INDICACION3 . "','" . $FORMULACION3 . "','" . $REGIMEN_DOSIS3 . "','" . $RUTA_ADMINISTRACION3 . "','" . $NUMERO_LOTE3 . "','" . $FECHA_EXPIRACION3 . "','" . $FECHA_INICIO3 . "','" . $TRATAMIENTO_CONTINUA3 . "','" . $MUESTRA_DISPONIBLE . "','" . $INFORMACION_MUESTRA . "','" . $RELACION_MEDICAMENTO1 . "','" . $RELACIONADO_DISPOSITIVO1 . "','" . $FECHA_INICIO_EVENTO1 . "','" . $DESENLACE1 . "','" . $FECHA_RECUPERACION1 . "','" . $FECHA_MUERTE1 . "','" . $CRITERIO_SERIEDAD1 . "','" . $CRITERIO_SERIEDAD_MUERTE1 . "','" . $CRITERIO_SERIEDAD_HOSPITALIZACION1 . "','" . $CRITERIO_SERIEDAD_AMENAZA1 . "','" . $CRITERIO_SERIEDAD_INCAPACIDAD1 . "','" . $CRITERIO_SERIEDAD_ANORMALIDAD1 . "','" . $CRITERIO_SERIEDAD_EVENTO1 . "','" . $CRITERIO_SERIEDAD_QUIRURGICA1 . "','" . $CAUSA_MUERTE1 . "','" . $DETALLES_EA1 . "','" . $RELACION_MEDICAMENTO2 . "','" . $RELACIONADO_DISPOSITIVO2 . "','" . $FECHA_INICIO_EVENTO2 . "','" . $DESENLACE2 . "','" . $FECHA_RECUPERACION2 . "','" . $FECHA_MUERTE2 . "','" . $CRITERIO_SERIEDAD2 . "','" . $CRITERIO_SERIEDAD_MUERTE2 . "','" . $CRITERIO_SERIEDAD_HOSPITALIZACION2 . "','" . $CRITERIO_SERIEDAD_AMENAZA2 . "','" . $CRITERIO_SERIEDAD_INCAPACIDAD2 . "','" . $CRITERIO_SERIEDAD_ANORMALIDAD2 . "','" . $CRITERIO_SERIEDAD_EVENTO2 . "','" . $CRITERIO_SERIEDAD_QUIRURGICA2 . "','" . $CAUSA_MUERTE2 . "','" . $DETALLES_EA2 . "','" . $RELACION_MEDICAMENTO3 . "','" . $RELACIONADO_DISPOSITIVO3 . "','" . $FECHA_INICIO_EVENTO3 . "','" . $DESENLACE3 . "','" . $FECHA_RECUPERACION3 . "','" . $FECHA_MUERTE3 . "','" . $CRITERIO_SERIEDAD3 . "','" . $CRITERIO_SERIEDAD_MUERTE3 . "','" . $CRITERIO_SERIEDAD_HOSPITALIZACION3 . "','" . $CRITERIO_SERIEDAD_AMENAZA3 . "','" . $CRITERIO_SERIEDAD_INCAPACIDAD3 . "','" . $CRITERIO_SERIEDAD_ANORMALIDAD3 . "','" . $CRITERIO_SERIEDAD_EVENTO3 . "','" . $CRITERIO_SERIEDAD_QUIRURGICA3 . "','" . $CAUSA_MUERTE3 . "','" . $DETALLES_EA3 . "','" . $INFORMACION_ADICIONAL . "','" . $NOMBRE_REPORTE . "','" . $ID_PACIENTE_FK . "','" . $MEDICAMENTO1 . "','" . $MEDICAMENTO2 . "','" . $MEDICAMENTO3 . "','" . $INFORMACION_EA1 . "','" . $INFORMACION_EA2 . "','" . $INFORMACION_EA3 . "','" . $FECHA_SUSPENCION1 . "','" . $FECHA_SUSPENCION2 . "','" . $FECHA_SUSPENCION3 . "','" . $NOMBRE_REPORTANTE . "','" . $TELEFONO_REPORTANTE . "','" . $TIPO_REPORTANTE . "')");
		echo mysqli_error($conex);
		$SELECT_EA = mysqli_query($conex,"SELECT * FROM bayer_evento_adverso AS EA
		INNER JOIN bayer_pacientes AS P ON P.ID_PACIENTE=EA.ID_PACIENTE_FK
		INNER JOIN bayer_tratamiento AS T ON T.ID_PACIENTE_FK=P.ID_PACIENTE
		WHERE EA.ID_PACIENTE_FK='" . $ID_PACIENTE_FK . "' ORDER BY EA.ID_EVENTO_ADVERSO DESC LIMIT 1");
		while ($fila1 = mysqli_fetch_array($SELECT_EA)) {
			$ID_EA = $fila1['ID_EVENTO_ADVERSO'];
		}
		if ($insertar) {
			include('../presentacion/pdf_evento_adverso.php');
	?>
			<span style="margin-top:5%;">
				<center>
					<img src="../presentacion/imagenes/chulo.png" width="118" height="117" style="width:100px; margin-top:100px;margin-top:5%;" />
				</center>
			</span>
			<p class="aviso3" style=" width:68.9%; margin:auto auto;">HA CREADO EXISITOSAMENTE EL EVENTO ADVERSO.</p>
			<br />
			<br />
			<center>
				<a href="../presentacion/form_paciente_seguimiento.php" target="info" class="btn_continuar"><img src="../presentacion/imagenes/BTN_CONTINUAR.png" style="width:152px; height:37px" /></a>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="../presentacion/form_evento_adverso.php?ID_PACIENTE=<?php echo $ID_PACIENTE_FK ?>" target="info" class="btn_continuar"><img src="../presentacion/imagenes/BOTON_AGREGAR2.png" style="width:152px; height:37px" /></a>
			</center>
		<?php
		} else {
		?>
			<span style="margin-top:5%;">
				<center>
					<img src="../presentacion/imagenes/advertencia.png" width="68" height="78" style="width:70px; margin-top:100px;margin-top:5%;" />
				</center>
			</span>
			<p class="error" style=" width:68.9%; margin:auto auto;">
				<span style="border-left-color:#fff">ERROR. VERIFIQUE LOS DATOS REGISTRADOS</span>
			</p>
			<br />
			<br />
			<center>
				<a href="javascript:history.go(-1)" target="info" class="btn_continuar"><img src="../presentacion/imagenes/BOTON_REGISTRAR_NARANJA.png" style="width:152px; height:37px" /></a>
			</center>
	<?php
		}
	}
	?>
</body>
</html>